Repository cordada/fd-django-accounts, pull requests merged in 2022-08, with the labels that each got.

#169 chore: Change Dependabot schedule interval from `daily` to `monthly`
  .github/dependabot.yml
Labels: task

#172 feat(management): Add management command `createsuperuser`
  fd_dj_accounts/management/__init__.py
  fd_dj_accounts/management/commands/__init__.py
  fd_dj_accounts/management/commands/createsuperuser.py
  tests/test_management.py
Labels: enhancement

#171 chore: Remove dependabot `time` and `timezone` params
  .github/dependabot.yml
Labels: task

#173 Release v0.1.4
  .bumpversion.cfg
  .circleci/config.yml
  .github/dependabot.yml
  HISTORY.rst
  fd_dj_accounts/__init__.py
  fd_dj_accounts/management/__init__.py
  fd_dj_accounts/management/commands/__init__.py
  fd_dj_accounts/management/commands/createsuperuser.py
  requirements_release.txt
  requirements_test.txt
  tests/test_management.py
Labels: task, kind: release

#174 chore(management): Improve management command `createsuperuser`
  fd_dj_accounts/management/__init__.py
  fd_dj_accounts/management/commands/createsuperuser.py
  tests/test_management.py
Labels: task

#176 chore: Add Make tasks for installation
  .circleci/config.yml
  Makefile
  README.rst
Labels: task
