Repository cordada/fd-django-accounts, pull requests merged in 2024-02, with the labels that each got.

#284 Change Python project structure from Flat layout to Src layout
  .bumpversion.cfg
  MANIFEST.in
  Makefile
  setup.cfg
  setup.py
  src/.keep
  src/fd_dj_accounts/__init__.py
  src/fd_dj_accounts/apps.py
  src/fd_dj_accounts/auth_backends.py
  src/fd_dj_accounts/base_models.py
  src/fd_dj_accounts/fixtures/regular.json
  src/fd_dj_accounts/management/__init__.py
  src/fd_dj_accounts/management/commands/__init__.py
  src/fd_dj_accounts/management/commands/createsuperuser.py
  src/fd_dj_accounts/migrations/0001_initial.py
  src/fd_dj_accounts/migrations/__init__.py
  src/fd_dj_accounts/models.py
  src/fd_dj_accounts/py.typed
  src/fd_dj_accounts/urls.py
  src/fd_dj_accounts/views.py
  src/tests/__init__.py
  src/tests/factories.py
  src/tests/settings.py
  src/tests/test_apps.py
  src/tests/test_auth_backends.py
  src/tests/test_factories.py
  src/tests/test_management.py
  src/tests/test_models.py
  src/tests/test_signals.py
  src/tests/urls.py
  src/tests/utils.py
  tox.ini
Labels: task

#286 Add Python project configuration
  pyproject.toml
Labels: task

#288 Release v0.9.0
  .bumpversion.cfg
  HISTORY.rst
  src/fd_dj_accounts/__init__.py
Labels: task, kind: release

#289 Deploy release v0.9.0
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.rst
  MANIFEST.in
  Makefile
  pyproject.toml
  requirements_release.txt
  requirements_test.txt
  setup.cfg
  setup.py
  src/.keep
  src/fd_dj_accounts/__init__.py
  src/fd_dj_accounts/apps.py
  src/fd_dj_accounts/auth_backends.py
  src/fd_dj_accounts/base_models.py
  src/fd_dj_accounts/fixtures/regular.json
  src/fd_dj_accounts/management/__init__.py
  src/fd_dj_accounts/management/commands/__init__.py
  src/fd_dj_accounts/management/commands/createsuperuser.py
  src/fd_dj_accounts/migrations/0001_initial.py
  src/fd_dj_accounts/migrations/__init__.py
  src/fd_dj_accounts/models.py
  src/fd_dj_accounts/py.typed
  src/fd_dj_accounts/urls.py
  src/fd_dj_accounts/views.py
  src/tests/__init__.py
  src/tests/factories.py
  src/tests/settings.py
  src/tests/test_apps.py
  src/tests/test_auth_backends.py
  src/tests/test_factories.py
  src/tests/test_management.py
  src/tests/test_models.py
  src/tests/test_signals.py
  src/tests/urls.py
  src/tests/utils.py
  tox.ini
Labels: task, kind: deploy
