Repository cordada/fd-django-accounts, pull requests merged in 2025-03, with the labels that each got.

#342 Release v0.13.0
  .bumpversion.cfg
  HISTORY.rst
  src/fd_dj_accounts/__init__.py
Labels: task, kind: release

#345 Improve test coverage exclusions
  .coveragerc.test.ini
Labels: task

#344 Require Python ≥3.9
  pyproject.toml
Labels: task

#346 Release v0.14.0
  .bumpversion.cfg
  HISTORY.rst
  src/fd_dj_accounts/__init__.py
Labels: task, kind: release

#347 Deploy release v0.14.0
  .bumpversion.cfg
  .coveragerc.test.ini
  HISTORY.rst
  pyproject.toml
  requirements_release.txt
  requirements_test.txt
  src/fd_dj_accounts/__init__.py
Labels: task, kind: deploy
